//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Payspace_NextGen.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class localdbEntities : DbContext
    {
        public localdbEntities()
            : base("name=localdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Calculation> Calculations { get; set; }
        public virtual DbSet<calculationDetail> calculationDetails { get; set; }
        public virtual DbSet<Employe> Employes { get; set; }
        public virtual DbSet<PostCode> PostCodes { get; set; }
        public virtual DbSet<TaxRate> TaxRates { get; set; }
        public virtual DbSet<TaxRateDetail> TaxRateDetails { get; set; }
        public virtual DbSet<TypeTax> TypeTaxes { get; set; }
    }
}
