//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Payspace_NextGen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxRateDetail
    {
        public int IdTaxRate { get; set; }
        public decimal From { get; set; }
        public Nullable<decimal> To { get; set; }
        public Nullable<decimal> Rate { get; set; }
    
        public virtual TaxRate TaxRate { get; set; }
    }
}
