//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Payspace_NextGen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxRate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaxRate()
        {
            this.PostCodes = new HashSet<PostCode>();
            this.TaxRateDetails = new HashSet<TaxRateDetail>();
        }
    
        public int Id { get; set; }
        public string NameTax { get; set; }
        public Nullable<int> TypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostCode> PostCodes { get; set; }
        public virtual TypeTax TypeTax { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaxRateDetail> TaxRateDetails { get; set; }
    }
}
