//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payspace_NextGen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PendenciaEsocial
    {
        public int Id { get; set; }
        public string Layout { get; set; }
        public System.DateTime DataHora { get; set; }
        public Nullable<int> Status { get; set; }
        public string Recibo { get; set; }
        public string Mensage { get; set; }
        public string Description { get; set; }
    
        public virtual Esocial_Layout Esocial_Layout { get; set; }
    }
}
