//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payspace_NextGen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateValue
    {
        public int Id { get; set; }
        public string TypeRate { get; set; }
        public decimal From { get; set; }
        public decimal To { get; set; }
        public decimal Rate { get; set; }
    
        public virtual Type Type { get; set; }
    }
}
